name: Submission [ENGLISH]
description: Submit cloning information for a paper
title: "PMID:XXXXXX"
labels: [bug, needs-triage]
body:
  - type: markdown
    attributes:
      value: "## Submitter Details (optional)"

  - type: input
    id: full-name
    attributes:
      label: "Full Name"
      description: "Enter your full name (optional)."
      placeholder: "Full Name"
    validations:
      required: false

  - type: input
    id: orcid
    attributes:
      label: "ORCID"
      description: "Enter your ORCID if you have one (optional)."
      placeholder: "ORCID:XXXX-XXXX-XXXX-XXXX"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Publication Details"

  - type: input
    id: pmid
    attributes:
      label: "PMID"
      description: "Enter the PMID of the paper."
      placeholder: "PMID:XXXXXX"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "Title"
      description: "Enter the title of the paper."
      placeholder: "Title of the paper"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Cloning Details"

  - type: dropdown
    id: cloning_detail_level
    attributes:
      label: "Cloning Detail Level"
      description: "Select the level of detail of the cloning information."
      options:
        - Cloning information missing
        - Cloning information present, but not sufficient to reproduce
        - Cloning information present and sufficient to reproduce
    validations:
      required: true

  - type: textarea
    id: cloning_text
    attributes:
      label: "Cloning Text (if available)"
      description: "Copy and paste the sections of the paper that describe cloning. Include all files by dropping them in the text box (primer lists, sequence files, etc.)"
      placeholder: "mCherry was amplified from plasmid xyz using primers abc and def, then [...]"
    validations:
      required: false

  - type: textarea
    id: cloning_strategies
    attributes:
      label: "Cloning Strategies"
      description: "Drag and drop all json files with cloning strategies (whatever you managed to extract from the paper, it can be simply the starting sequences, primers, etc.)."
      placeholder: "Drop your files here"
    validations:
      required: false

  - type: textarea
    id: missing_information
    attributes:
      label: "Missing information (if any)"
      description: "Describe the information or sequences that would have been needed to reproduce the cloning, but were missing."
      placeholder: "The sequence of plasmids xyz was not provided and we could not find it online, the primers used for gibson assembly were not provided, etc."
    validations:
      required: false

  - type: textarea
    id: present_information
    attributes:
      label: "Present information (if any)"
      description: "If you did not manage to reproduce the cloning, describe what information you could find in the paper, even if it is not sufficient to reproduce the cloning."
      placeholder: "The sequence of plasmids xyz was provided in the supplementary material, the primers used for gibson assembly were provided in the supplementary material, etc."
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Any additional notes or comments."